In [1]:
# Labial 

import sys

import numpy as np 
import pandas as pd 
import os 
import pickle
from pathlib import Path
REPO_ROOT = Path.cwd().resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "code"))
from cell_groups import *
from color_utils import * 
from make_network import *
from make_network_utils import *
from analysis_of_simulation_result import *

In [2]:
# # Rank data to Set color of nodes 
# def make_rank_color_info(rank_df, top_n=20, base_color="#FF0066", default_color="#777777"):
#     num_top_ranked = (rank_df <= top_n).sum(axis=1)

#     return {
#         tid: (
#             get_graded_color(base_color, int(num))
#             if num > 2
#             else default_color
#         )
#         for tid, num in num_top_ranked.items()
#     }


Rank_DATA_DIR = Path.cwd().resolve().parents[0]/'figure5Q,R/data'
tarsal_sweet_rank_df = pd.read_parquet(Rank_DATA_DIR/'tarsal_sweet_rank.parquet')
labial_sweet_rank_df = pd.read_parquet(Rank_DATA_DIR/'labial_sweet_rank.parquet')
tarsal_geosmin_rank_df = pd.read_parquet(Rank_DATA_DIR/'tarsal_geosmin_rank.parquet')
labial_geosmin_rank_df = pd.read_parquet(Rank_DATA_DIR/'labial_geosmin_rank.parquet')


# color_info_tarsal_sweet = make_rank_color_info(
#     tarsal_sweet_rank_df,
#     top_n=20,
#     base_color="#0066FF",
# )

# color_info_labial_sweet = make_rank_color_info(
#     labial_sweet_rank_df,
#     top_n=20,
#     base_color="#00AA66",
# )

# color_info_tarsal_geosmin = make_rank_color_info(
#     tarsal_geosmin_rank_df,
#     top_n=20,
#     base_color="#FF0066",
# )


# color_info_labial_geosmin = make_rank_color_info(
#     labial_geosmin_rank_df,
#     top_n=20,
#     base_color="#FF0066",
# )

In [3]:
sez_ids = np.concatenate(list(sez.values()))
fid2sez_g = {c:t for t,cids in sez.items() for c in cids}

gids = np.unique(np.concatenate([tarsal_sweet_rank_df.index,labial_sweet_rank_df.index,tarsal_geosmin_rank_df.index,labial_geosmin_rank_df.index]))

canonical_name = []
for g in gids:
    g = int(g)
    fids = target_ids_valid_all[g_info_all==g]
    if np.any(np.isin(fids,sez_ids)):
        canonical_name.append(fid2sez_g[fids[np.isin(fids,sez_ids)][0]])
    else:
        canonical_name.append(str(g))
gid2canonical_name = dict(zip(gids,canonical_name))
gid2canonical_name['control'] = 'control'

In [4]:

# ## add another sweet pathway node to adjust node location 
# tarsal_sweetG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure5_new-order/functional_network/sweet/tarsal/tarsal_hm_thresholded_0.1.gexf')
# labial_sweetG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure5_new-order/functional_network/sweet/labial/labial_hm_thresholded_0.1.gexf')
# tarsal_sgG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure5_new-order/functional_network/geosmin/tarsal/tarsal_av1a1_hm_thresholded_0.1_0.2.gexf')
# labial_sgG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure8/Network_with_necessity_with_spike_pattern_fixed/Merged_network_new_criterion/labial_av1a1/labial_av1a1_hm_thresholded_0.1_0.2.gexf')
# for n in labial_sgG.nodes(): # need to be changed when processing another modality 
#     color_info[n] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
    
    
# num_th1 = 3

# counts = (tarsal_sweet_rank_df <= 20).sum(axis=1)
# num_per_concent_sweet = counts.astype(int).to_dict()
# in_network_sweet = counts[counts >= num_th1].index.astype(int).to_numpy()

# counts = (tarsal_geosmin_rank_df <= 20).sum(axis=1)
# num_per_concent_av1a1 = counts.astype(int).to_dict()
# in_network_av1a1 = counts[counts >= num_th1].index.astype(int).to_numpy()



# c_to_add_sweet = target_ids_valid_all[np.isin(g_info_all,in_network_sweet)]
# c_to_add_av1a1 = target_ids_valid_all[np.isin(g_info_all,in_network_av1a1)]



# base_green = hex_to_rgba("#0066FF")
# colors = []
# for v in num_per_concent_sweet.values():
#     if v == 4:
#         rgba = base_green
#     else:
#         light_rgb = lighten_color(base_green, factor=0.5)  # 흐린 정도 조절
#         rgba = np.array([*light_rgb, 1])
    
#     colors.append(dict(zip(['a','r','g','b'], [rgba[3], rgba[0], rgba[1], rgba[2]])))

# color_info.update(dict(zip([gid2canonical_name[x] for x in num_per_concent_sweet.keys()], colors)))


# color_info['atGRN'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['TPN1'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['MN9'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}

# cells_in_new_net = np.concatenate([c_to_add_sweet,atGRNs,TPN1,mn9,c_to_add_av1a1,av1a1,or56a,da2pn])




# base_red = hex_to_rgba("#FF0066")
# colors = []
# for v in num_per_concent_av1a1.values():
#     if v == 4:
#         rgba = base_red
#     else:
#         light_rgb = lighten_color(base_red, factor=0.5)  # 흐린 정도 조절
#         rgba = np.array([*light_rgb, 1])
    
#     colors.append(dict(zip(['a','r','g','b'], [rgba[3], rgba[0], rgba[1], rgba[2]])))

# color_info.update(dict(zip([gid2canonical_name[x] for x in num_per_concent_av1a1.keys()], colors)))

# color_info['av1a1'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['DA2_PN'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['Or56a'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}




# thisG = make_meta_network(cells_in_new_net)
# dummy_nodes = pickle.load(open('/volume_4/research/seongbong/flywire/geosmin_project_version_update/figure5/functional_network_final-base_PER/geosmin_labial/labial_core_nodes.pkl','rb'))
# to_add = np.setdiff1d(dummy_nodes,thisG.nodes)
# thisG.add_nodes_from(list(to_add))
# for x in to_add:
#     color_info[x] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# # thisG.add_nodes_from(list(labial_sweetG.nodes()))

# for n in thisG.nodes():
#     if n in tarsal_sweetG.nodes():
#         thisG.nodes[n]['modality'] = 'tarsal'
#     elif n in labial_sweetG.nodes():
#         thisG.nodes[n]['modality'] = 'labial'
#     else:
#         thisG.nodes[n]['modality'] = 'geosmin'
# for n in to_add:
#     thisG.nodes[n]['modality'] = 'dummy'
        
# info = pd.read_csv('/volume_4/research/seongbong/flywire/geosmin_project_version_update/figure5/functional_network_final-base_PER/merged_using_first_positions_0_1000.csv')
# node_loc = {}
# for i in info.Id.values:
#     temp = {}
#     temp['x'] = info[info.Id.values==i]['X'].values[0]
#     temp['y'] = info[info.Id.values==i]['Y'].values[0]
#     temp['z'] = 0
#     node_loc[i] = temp

# for i,g in enumerate(np.setdiff1d(list(thisG.nodes()),list(node_loc.keys()))):
#     node_loc[g] = node_loc['horntail'].copy()
#     node_loc[g]['x'] += 100*(i+1)
# metaG_with_pos = set_node_location(thisG,node_loc)


# metaG_with_pos_color = set_node_color(metaG_with_pos,color_info)
# rm_edges = []
# for u,v in metaG_with_pos_color.edges():
#     if metaG_with_pos_color[u][v]['weight'] < 7:
#         rm_edges.append((u,v))
#     else:
#         metaG_with_pos_color[u][v]['weight'] = np.log2(metaG_with_pos_color[u][v]['weight'])
        
        
        
# metaG_with_pos_color_rm = metaG_with_pos_color.copy()


# # for n in metaG_with_pos_color_rm.nodes():
# #     if n in canonical2name.keys():
# #         metaG_with_pos_color_rm.nodes[n]['codex_name'] = str(canonical2name[n])
# #     else:
# #         metaG_with_pos_color_rm.nodes[n]['codex_name'] = str(n)

# metaG_with_pos_color_rm.remove_edges_from(rm_edges)
# metaG_with_pos_color_rm = set_edge_color(metaG_with_pos_color_rm)
# nx.write_gexf(metaG_with_pos_color_rm,'tarsal_av1a1_core.gexf')

# recurrent_edges = [(u,v) for u,v in metaG_with_pos_color_rm.edges() if (metaG_with_pos_color_rm.nodes[u]['modality'],metaG_with_pos_color_rm.nodes[v]['modality'])==('tarsal','geosmin')]
# metaG_with_pos_color_rm.remove_edges_from(recurrent_edges)
# metaG_with_pos_color_rm = set_edge_color(metaG_with_pos_color_rm)
# nx.write_gexf(metaG_with_pos_color_rm,'tarsal_av1a1_core_remove_recurrent.gexf')

In [5]:

# ## add another sweet pathway node to adjust node location 
# tarsal_sweetG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure5_new-order/functional_network/sweet/tarsal/tarsal_hm_thresholded_0.1.gexf')
# labial_sweetG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure5_new-order/functional_network/sweet/labial/labial_hm_thresholded_0.1.gexf')
# tarsal_sgG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure5_new-order/functional_network/geosmin/tarsal/tarsal_av1a1_hm_thresholded_0.1_0.2.gexf')
# labial_sgG = nx.read_gexf('/volume_4/research/seongbong/flywire/geosmin_project/figure/figure8/Network_with_necessity_with_spike_pattern_fixed/Merged_network_new_criterion/labial_av1a1/labial_av1a1_hm_thresholded_0.1_0.2.gexf')
# for n in tarsal_sgG.nodes(): # need to be changed when processing another modality 
#     color_info[n] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
    
    
# num_th1 = 3

# counts = (labial_sweet_rank_df <= 20).sum(axis=1)
# num_per_concent_sweet = counts.astype(int).to_dict()
# in_network_sweet = counts[counts >= num_th1].index.astype(int).to_numpy()

# counts = (labial_geosmin_rank_df <= 20).sum(axis=1)
# num_per_concent_av1a1 = counts.astype(int).to_dict()
# in_network_av1a1 = counts[counts >= num_th1].index.astype(int).to_numpy()



# c_to_add_sweet = target_ids_valid_all[np.isin(g_info_all,in_network_sweet)]
# c_to_add_av1a1 = target_ids_valid_all[np.isin(g_info_all,in_network_av1a1)]

# # av1a1 

# base_green = hex_to_rgba("#00AA66")
# colors = []
# for v in num_per_concent_sweet.values():
#     if v == 4:
#         rgba = base_green
#     else:
#         light_rgb = lighten_color(base_green, factor=0.5)  # 흐린 정도 조절
#         rgba = np.array([*light_rgb, 1])
    
#     colors.append(dict(zip(['a','r','g','b'], [rgba[3], rgba[0], rgba[1], rgba[2]])))

# color_info.update(dict(zip([gid2canonical_name[x] for x in num_per_concent_sweet.keys()], colors)))


# color_info['atGRN'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['TPN1'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['MN9'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}

# # av1a1 
# cells_in_new_net = np.concatenate([c_to_add_sweet,labial_sweet,mn9,c_to_add_av1a1,av1a1,or56a,da2pn])




# base_red = hex_to_rgba("#FF0066")
# colors = []
# for v in num_per_concent_av1a1.values():
#     if v == 4:
#         rgba = base_red
#     else:
#         light_rgb = lighten_color(base_red, factor=0.5)  # 흐린 정도 조절
#         rgba = np.array([*light_rgb, 1])
    
#     colors.append(dict(zip(['a','r','g','b'], [rgba[3], rgba[0], rgba[1], rgba[2]])))

# color_info.update(dict(zip([gid2canonical_name[x] for x in num_per_concent_av1a1.keys()], colors)))

# color_info['av1a1'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['DA2_PN'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# color_info['Or56a'] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}




# thisG = make_meta_network(cells_in_new_net)
# dummy_nodes = pickle.load(open('/volume_4/research/seongbong/flywire/geosmin_project_version_update/figure5/functional_network_final-base_PER/geosmin_tarsal/tarsal_core_nodes.pkl','rb'))
# to_add = np.setdiff1d(dummy_nodes,thisG.nodes)
# thisG.add_nodes_from(list(to_add))
# for x in to_add:
#     color_info[x] = {'a': 1, 'r': 125, 'g': 125, 'b': 125}
# # thisG.add_nodes_from(list(labial_sweetG.nodes()))

# for n in thisG.nodes():
#     if n in tarsal_sweetG.nodes():
#         thisG.nodes[n]['modality'] = 'tarsal'
#     elif n in labial_sweetG.nodes():
#         thisG.nodes[n]['modality'] = 'labial'
#     else:
#         thisG.nodes[n]['modality'] = 'geosmin'
# for n in to_add:
#     thisG.nodes[n]['modality'] = 'dummy'
        
# info = pd.read_csv('/volume_4/research/seongbong/flywire/geosmin_project_version_update/figure5/functional_network_final-base_PER/merged_using_first_positions_0_1000.csv')
# node_loc = {}
# for i in info.Id.values:
#     temp = {}
#     temp['x'] = info[info.Id.values==i]['X'].values[0]
#     temp['y'] = info[info.Id.values==i]['Y'].values[0]
#     temp['z'] = 0
#     node_loc[i] = temp

# for i,g in enumerate(np.setdiff1d(list(thisG.nodes()),list(node_loc.keys()))):
#     node_loc[g] = node_loc['horntail'].copy()
#     node_loc[g]['x'] += 100*(i+1)
# metaG_with_pos = set_node_location(thisG,node_loc)


# metaG_with_pos_color = set_node_color(metaG_with_pos,color_info)
# rm_edges = []
# for u,v in metaG_with_pos_color.edges():
#     if metaG_with_pos_color[u][v]['weight'] < 7:
#         rm_edges.append((u,v))
#     else:
#         metaG_with_pos_color[u][v]['weight'] = np.log2(metaG_with_pos_color[u][v]['weight'])
        
        
        
# metaG_with_pos_color_rm = metaG_with_pos_color.copy()


# # for n in metaG_with_pos_color_rm.nodes():
# #     if n in canonical2name.keys():
# #         metaG_with_pos_color_rm.nodes[n]['codex_name'] = str(canonical2name[n])
# #     else:
# #         metaG_with_pos_color_rm.nodes[n]['codex_name'] = str(n)

# metaG_with_pos_color_rm.remove_edges_from(rm_edges)
# metaG_with_pos_color_rm = set_edge_color(metaG_with_pos_color_rm)
# nx.write_gexf(metaG_with_pos_color_rm,'labial_av1a1_core.gexf')

# recurrent_edges = [(u,v) for u,v in metaG_with_pos_color_rm.edges() if (metaG_with_pos_color_rm.nodes[u]['modality'],metaG_with_pos_color_rm.nodes[v]['modality'])==('tarsal','geosmin')]
# metaG_with_pos_color_rm.remove_edges_from(recurrent_edges)
# metaG_with_pos_color_rm = set_edge_color(metaG_with_pos_color_rm)
# nx.write_gexf(metaG_with_pos_color_rm,'labial_av1a1_core_remove_recurrent.gexf')

In [6]:
BASE_DIR = Path(
    "/volume_4/research/seongbong/flywire/geosmin_project"
)

UPDATED_BASE_DIR = Path(
    "/volume_4/research/seongbong/flywire/"
    "geosmin_project_version_update"
)

graph_paths = {
    "tarsal_sweet": (
        BASE_DIR
        / "figure/figure5_new-order/functional_network/"
          "sweet/tarsal/tarsal_hm_thresholded_0.1.gexf"
    ),
    "labial_sweet": (
        BASE_DIR
        / "figure/figure5_new-order/functional_network/"
          "sweet/labial/labial_hm_thresholded_0.1.gexf"
    ),
    "tarsal_geosmin": (
        BASE_DIR
        / "figure/figure5_new-order/functional_network/"
          "geosmin/tarsal/"
          "tarsal_av1a1_hm_thresholded_0.1_0.2.gexf"
    ),
    "labial_geosmin": (
        BASE_DIR
        / "figure/figure8/"
          "Network_with_necessity_with_spike_pattern_fixed/"
          "Merged_network_new_criterion/labial_av1a1/"
          "labial_av1a1_hm_thresholded_0.1_0.2.gexf"
    ),
}

graphs = load_gexf_graphs(graph_paths)

tarsal_sweetG = graphs["tarsal_sweet"]
labial_sweetG = graphs["labial_sweet"]
tarsal_sgG = graphs["tarsal_geosmin"]
labial_sgG = graphs["labial_geosmin"]

In [17]:
TOP_N = 20
MIN_COUNT = 3
N_CONCENTRATIONS = tarsal_sweet_rank_df.shape[1]

sweet_rank_counts, in_network_sweet = (
    get_rank_counts_and_selected_nodes(
        tarsal_sweet_rank_df,
        top_n=TOP_N,
        min_count=MIN_COUNT,
    )
)

geosmin_rank_counts, in_network_av1a1 = (
    get_rank_counts_and_selected_nodes(
        tarsal_geosmin_rank_df,
        top_n=TOP_N,
        min_count=MIN_COUNT,
    )
)


c_to_add_sweet = group_ids_to_cell_ids(
    in_network_sweet,
    target_ids_valid_all,
    g_info_all,
)

c_to_add_av1a1 = group_ids_to_cell_ids(
    in_network_av1a1,
    target_ids_valid_all,
    g_info_all,
)

color_info = {}

# 다른 modality의 위치 보정용 node
set_gray_node_colors(
    color_info,
    labial_sgG.nodes,
)


sweet_colors = make_rank_color_info(
    sweet_rank_counts,
    gid2canonical_name=gid2canonical_name,
    base_color="#0066FF",
    max_count=N_CONCENTRATIONS,
)

geosmin_colors = make_rank_color_info(
    geosmin_rank_counts,
    gid2canonical_name=gid2canonical_name,
    base_color="#FF0066",
    max_count=N_CONCENTRATIONS,
)

color_info.update(sweet_colors)
color_info.update(geosmin_colors)

set_gray_node_colors(
    color_info,
    [
        "atGRN",
        "TPN1",
        "MN9",
        "av1a1",
        "DA2_PN",
        "Or56a",
    ],
)



cells_in_new_net = combine_unique_cells(
    c_to_add_sweet,
    atGRNs,
    TPN1,
    mn9,
    c_to_add_av1a1,
    av1a1,
    or56a,
    da2pn,
)

thisG = make_meta_network(cells_in_new_net)


dummy_node_path = (
    UPDATED_BASE_DIR
    / "figure5/functional_network_final-base_PER/"
      "geosmin_labial/labial_core_nodes.pkl"
)

thisG, dummy_nodes = add_dummy_nodes_from_pickle(
    thisG,
    pickle_path=dummy_node_path,
    color_info=color_info,
)


thisG = assign_node_modalities(
    thisG,
    tarsal_nodes=tarsal_sweetG.nodes,
    labial_nodes=labial_sweetG.nodes,
    dummy_nodes=dummy_nodes,
)


position_csv_path = (
    UPDATED_BASE_DIR
    / "figure5/functional_network_final-base_PER/"
      "merged_using_first_positions_0_1000.csv"
)

node_locations = load_node_locations(position_csv_path)

node_locations = add_missing_node_locations(
    thisG,
    node_locations,
    reference_node="horntail",
    x_spacing=100,
)

metaG_with_pos = set_node_location(
    thisG,
    node_locations,
)

metaG_with_pos_color = set_node_color(
    metaG_with_pos,
    color_info,
)

core_graph = threshold_and_transform_edges(
    metaG_with_pos_color,
    min_weight=7,
    weight_transform=np.log2,
)

core_graph = set_edge_color(core_graph)

nx.write_gexf(
    core_graph,
    "tarsal_av1a1_core.gexf",
)

core_graph_without_recurrent = remove_cross_modality_edges(
    core_graph,
    source_modality="tarsal",
    target_modality="geosmin",
)

core_graph_without_recurrent = set_edge_color(
    core_graph_without_recurrent
)

nx.write_gexf(
    core_graph_without_recurrent,
    "tarsal_av1a1_core_remove_recurrent.gexf",
)

In [18]:
sweet_neurons = [gid2canonical_name[str(x)] for x in in_network_sweet]

def get_lm_match(x):
    try:
        int(x)
        return 'No'
    except (ValueError, TypeError):
        return 'Yes'

supp_table = pd.DataFrame({
    'Neuron type': sweet_neurons,
    'Previously characterized': '',
    'Genetic driver': '',
    'LM match': [get_lm_match(x) for x in sweet_neurons],
    'Functional evidence': '',
    'Reference': ''
})
supp_table = supp_table.sort_values(
    'LM match',
    key=lambda x: x.map({'Yes': 0, 'No': 1})
).reset_index(drop=True)


supp_table

,Neuron type,Previously characterized,Genetic driver,LM match,Functional evidence,Reference
0,FDG,,,Yes,,
1,bract,,,Yes,,
2,rounddown,,,Yes,,
3,sink and sync,,,Yes,,
4,roundup,,,Yes,,
5,3,,,No,,
6,535,,,No,,
7,5342,,,No,,
8,5467,,,No,,
9,5523,,,No,,
10,6286,,,No,,
11,6114,,,No,,
12,7014,,,No,,
13,7272,,,No,,
14,8445,,,No,,
15,8586,,,No,,
16,8689,,,No,,
17,9036,,,No,,

In [8]:
TOP_N = 20
MIN_COUNT = 3
N_CONCENTRATIONS = labial_sweet_rank_df.shape[1]

sweet_rank_counts, in_network_sweet = (
    get_rank_counts_and_selected_nodes(
        labial_sweet_rank_df,
        top_n=TOP_N,
        min_count=MIN_COUNT,
    )
)

geosmin_rank_counts, in_network_av1a1 = (
    get_rank_counts_and_selected_nodes(
        labial_geosmin_rank_df,
        top_n=TOP_N,
        min_count=MIN_COUNT,
    )
)


c_to_add_sweet = group_ids_to_cell_ids(
    in_network_sweet,
    target_ids_valid_all,
    g_info_all,
)

c_to_add_av1a1 = group_ids_to_cell_ids(
    in_network_av1a1,
    target_ids_valid_all,
    g_info_all,
)


color_info = {}

# 반대 modality의 geosmin network node를 위치 보정용 회색 node로 사용
set_gray_node_colors(
    color_info,
    tarsal_sgG.nodes,
)


sweet_colors = make_rank_color_info(
    sweet_rank_counts,
    gid2canonical_name=gid2canonical_name,
    base_color="#00AA66",
    max_count=N_CONCENTRATIONS,
)

geosmin_colors = make_rank_color_info(
    geosmin_rank_counts,
    gid2canonical_name=gid2canonical_name,
    base_color="#FF0066",
    max_count=N_CONCENTRATIONS,
)

color_info.update(sweet_colors)
color_info.update(geosmin_colors)


set_gray_node_colors(
    color_info,
    [
        "MN9",
        "av1a1",
        "DA2_PN",
        "Or56a",
    ],
)


cells_in_new_net = combine_unique_cells(
    c_to_add_sweet,
    labial_sweet,
    mn9,
    c_to_add_av1a1,
    av1a1,
    or56a,
    da2pn,
)

thisG = make_meta_network(cells_in_new_net)


dummy_node_path = (
    UPDATED_BASE_DIR
    / "figure5/functional_network_final-base_PER/"
      "geosmin_tarsal/tarsal_core_nodes.pkl"
)

thisG, dummy_nodes = add_dummy_nodes_from_pickle(
    thisG,
    pickle_path=dummy_node_path,
    color_info=color_info,
)


thisG = assign_node_modalities(
    thisG,
    tarsal_nodes=tarsal_sweetG.nodes,
    labial_nodes=labial_sweetG.nodes,
    dummy_nodes=dummy_nodes,
)


position_csv_path = (
    UPDATED_BASE_DIR
    / "figure5/functional_network_final-base_PER/"
      "merged_using_first_positions_0_1000.csv"
)

node_locations = load_node_locations(position_csv_path)

node_locations = add_missing_node_locations(
    thisG,
    node_locations,
    reference_node="horntail",
    x_spacing=100,
)

metaG_with_pos = set_node_location(
    thisG,
    node_locations,
)


metaG_with_pos_color = set_node_color(
    metaG_with_pos,
    color_info,
)


core_graph = threshold_and_transform_edges(
    metaG_with_pos_color,
    min_weight=7,
    weight_transform=np.log2,
)

core_graph = set_edge_color(core_graph)


nx.write_gexf(
    core_graph,
    "labial_av1a1_core.gexf",
)


core_graph_without_recurrent = remove_cross_modality_edges(
    core_graph,
    source_modality="labial",
    target_modality="geosmin",
)

core_graph_without_recurrent = set_edge_color(
    core_graph_without_recurrent
)


nx.write_gexf(
    core_graph_without_recurrent,
    "labial_av1a1_core_remove_recurrent.gexf",
)

In [10]:
in_network_sweet

array([ 1485, 15622,    17,  2158,  2301,  2712,  3032,  4217,  4973,
         535,  5523,  6286,  7028,  7272,   758,  7625,  8445,  8586,
        8781])

In [16]:
sweet_neurons = [gid2canonical_name[str(x)] for x in in_network_sweet]

def get_lm_match(x):
    try:
        int(x)
        return 'No'
    except (ValueError, TypeError):
        return 'Yes'

supp_table = pd.DataFrame({
    'Neuron type': sweet_neurons,
    'Previously characterized': '',
    'Genetic driver': '',
    'LM match': [get_lm_match(x) for x in sweet_neurons],
    'Functional evidence': '',
    'Reference': ''
})
supp_table = supp_table.sort_values(
    'LM match',
    key=lambda x: x.map({'Yes': 0, 'No': 1})
).reset_index(drop=True)


supp_table

,Neuron type,Previously characterized,Genetic driver,LM match,Functional evidence,Reference
0,FDG,,,Yes,,
1,clavicle,,,Yes,,
2,bract,,,Yes,,
3,rounddown,,,Yes,,
4,G2N-1,,,Yes,,
5,roundup,,,Yes,,
6,2158,,,No,,
7,17,,,No,,
8,2301,,,No,,
9,2712,,,No,,
10,4973,,,No,,
11,535,,,No,,
12,6286,,,No,,
13,5523,,,No,,
14,7272,,,No,,
15,758,,,No,,
16,8445,,,No,,
17,8586,,,No,,
18,8781,,,No,,

In [19]:
g_info_all[target_ids_valid_all==720575940621261296]

array([535.])